### ISSUE TITLE
Overloading term constructors

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Gatlab.jl#14]
When I define the theory of monoidal categories, I want to be able to use \otimes for both object composition and morphism composition. I should be able to use type inference to figure out which one I mean when parsing a term, which should be possible by only looking at the type constructors, and then these should get parsed into different de Bruijn levels.

**Comment by kris-brown** [comment]
Addressed by signatures in https://github.com/AlgebraicJulia/Gatlab.jl/pull/81
