### ISSUE TITLE
Normal form for associative, unital operations

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Gatlab.jl#59]
A standard trick in computer algebra, including in the current GAT implementation in Catlab (#57), is to normalize binary expressions for associative operations by using trees with arbitrary branching. Gatlab should implement this too.

Note that this transformation is *not* handled by generic rewriting, but at the level of the data structures themselves.

**Comment by olynch** [comment]
This is split into #88 and #41; one issue for GATExprs and one issue for AlgTerms.
