### ISSUE TITLE
Model -> Model family

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Gatlab.jl#63]
I propose that we use the term "model system" for what we previously called a "model" of a GAT. Instances of a model system struct are individual models. Some model systems consist of just a single model (i.e. zero field structs), but in general a model system might encompass many values of the struct, and thus many "models".

**Comment by epatters** [comment]
I agree that it is good to distinguish a particular model of the GAT from a struct that specifies many different models at once. I'm not sure about the term "model system" though. Maybe "model family," being short for "a family of models"?

**Comment by olynch** [comment]
I like model family; family is more specific to the usage of "system" that I had in mind (i.e., analogous to "solar system").

**Comment by jpfairbanks** [comment]
So is model family taking the place of the logician's Model. And model is now referring to the entities in the model family?

**Comment by KevinArlin** [comment]
I feel like that's not what Owen meant but it's also not clear to me. Is it instead that a model family is going to be a struct such that any instance of the struct is an actual model of the theory, e.g. `struct FinCat int n end` is a model family for the GAT of categories?

**Comment by KevinArlin** [comment]
lol, the GAT of sets I guess

**Comment by olynch** [comment]
No, the logician's model corresponds to specific instances of the struct that corresponds to the model family. For instance, we might have a model family

```julia
struct SliceCat{Ob, Hom, C<:Model{Category, Tuple{Ob, Hom}} <: Model{Category, Tuple{Tuple{Ob, Hom}, Hom}}
  cat::C
  over::Ob
end
```

Each value of `SliceCat` corresponds to a specific model.

**Comment by jpfairbanks** [comment]
Ok so SliceCat is a model family. And then what that type signature says is that each instance of SliceCat is a model of the theory of Categories. 

What do we call the structs that will store the objects and morphisms in a particular model (instance of SliceCat)?

**Comment by olynch** [comment]
> Ok so SliceCat is a model family. And then what that type signature says is that each instance of SliceCat is a model of the theory of Categories.

Yes, exactly.

> What do we call the structs that will store the objects and morphisms in a particular model (instance of SliceCat)?

Good question, I don't yet have a name for that. Any suggestions?
