### ISSUE TITLE
ThX.Th

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Gatlab.jl#68]
In #67, we name the structs corresponding to theories by `ThX.Th`, i.e. `ThCategory.Th`, etc.

This is weird and awkward. Alternatives:

- `Category.Th`
- `ThCategory.T`

Thoughts @epatters, @jpfairbanks?

**Comment by epatters** [comment]
We fairly recently refactored Catlab to use the `Th` prefix for exported GATs, and I'd like to keep that convention. With that in mind, maybe `ThCategory.T`?

**Comment by olynch** [comment]
Sure, that sounds good to me.
